
export const login = '/login/landing' //用户登陆
export const check = '/login/check'//注册
export const logout = '/login/logout'//退出登陆
export const employee = '/employee/list '//员工列表
export const employeeAdd = '/employee/add' //新增员工
export const employeeView = '/employee/view'//员工详情
export const employeeUpdate = '/employee/update' //修改员工
export const noticeAdd = '/notice/add' //新增公告
export const noticeList = '/notice/list' //公告列表
export const noticeView = '/notice/view' //公告详情
export const noticeUpdate = '/notice/update'//修改公告
export const dictionaryAdd='/dictionary/add' //新增字典
export const dictionaryList='/dictionary/list' //字典列表
export const dictionaryView='/dictionary/view' //字典详情
export const dictionaryUpdate='/dictionary/update' //字典修改
export const noticPageNoticList='/notice/page/notice/list' //首页公告显示
export const loginUpload='/login/upload' //上传
export const applyList='/apply/list'//获取申请数据列表
export const applyAdd='/apply/add' //添加申请数据
