
export const login = '/login/landing' //用户登陆
export const check = '/login/check'//注册
export const logout = '/login/logout'//退出登陆
export const employee = '/employee/list '//员工列表
export const employeeList = '/employee/homeList '//员工列表
export const employeeAdd = '/employee/add' //新增员工
export const employeeView = '/employee/view'//员工详情
export const employeeUpdate = '/employee/update' //修改员工
export const noticeAdd = '/notice/add' //新增公告
export const noticeList = '/notice/list' //公告列表
export const noticeView = '/notice/view' //公告详情
export const noticeUpdate = '/notice/update'//修改公告
export const dictionaryAdd='/dictionary/add' //新增字典
export const dictionaryList='/dictionary/list' //字典列表
export const dictionaryView='/dictionary/view' //字典详情
export const dictionaryUpdate='/dictionary/update' //字典修改
export const noticPageNoticList='/notice/page/notice/list' //首页公告显示
export const loginUpload='/login/upload' //上传
export const applyList='/apply/list'//获取申请数据列表
export const applyAdd='/apply/add' //添加申请数据

export const dictionaryGetapi = "/dictionary/getapi"//外部获取字典信息
export const oderList = "/oder/lits"//订单列表查询
export const oderAdd = "/oder/add"//订单创建
export const oderView = "/oder/view"//订单详情
export const oderUpdate = "/oder/update"//修改订单
export const add = "/add"//增加评论

export const serveAdd = "/serviceType/add"//增加服务类型
export const serveList = "/serviceType/list"//获取服务类型列表
export const serveView = "/serviceType/view"//获取服务类型详情
export const serveUpdate = "/serviceType/update"//获取服务类型详情
export const serveGet = "/serviceType/getApi"//获取具体服务
export const customerAdd = "/customer/add"//增加客户
export const correlationAdd = "/correlation/add"//添加员工服务
export const custormerList = "/customer/list"//获取客户列表
export const custormerView = "/customer/viewByCode"//获取客户详情
export const custormerUpdate = "/customer/update"//修改客户
export const correlationGet ="/correlation/getList"//获取员工管理服务
export const correlationUpdate = "/correlation/update"//修改员工关联服务
export const wageList = "/wage/list"//获取工资列表
export const wageView ="/wage/view"//获取工资详情
export const wageUpdate = "/wage/update"//修改工资
export const employeeViewCode = "/employee/viewByCode"//获取员工个人信息
export const wagesGetList = "/wages/getList"//工资条列表
export const wagesAdd = "/wages/add"//工资条添加
export const wagesView = "/wages/view"//工资条详情
export const wagesUpdate = '/wages/update'//工资条修改